"""Initial migration

Revision ID: 46e1b12e8bcf
Revises: 
Create Date: 2025-09-02 16:35:55.538889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632fbd0fdb81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS_NUE',
    sa.Column('nue_id', sa.Integer(), nullable=False),
    sa.Column('nue_nickname', sa.String(length=100), nullable=False),
    sa.Column('nue_hashedpassword', sa.String(length=500), nullable=False),
    sa.Column('nue_recordcreation', sa.TIMESTAMP(), nullable=False),
    sa.Column('nue_recordmodification', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('nue_id')
    )
    op.create_table('EVENTS_NEV',
    sa.Column('nev_id', sa.Integer(), nullable=False),
    sa.Column('nev_title', sa.String(length=100), nullable=False),
    sa.Column('nev_description', sa.String(length=500), nullable=True),
    sa.Column('nev_starttime', sa.TIMESTAMP(), nullable=False),
    sa.Column('nev_endtime', sa.TIMESTAMP(), nullable=False),
    sa.Column('nue_nev_n_fk', sa.Integer(), nullable=True),
    sa.Column('nev_recordcreation', sa.TIMESTAMP(), nullable=False),
    sa.Column('nev_recordmodification', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['nue_nev_n_fk'], ['USERS_NUE.nue_id'], ),
    sa.PrimaryKeyConstraint('nev_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EVENTS_NEV')
    op.drop_table('USERS_NUE')
    # ### end Alembic commands ###
